name: Test
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test:
#    Где запускаем
    runs-on: ubuntu-latest
#    Что делаем
    steps:
#   Выкачмваем репозиторий
    - uses: actions/checkout@v4
#      Настраиваем Java
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
#   Запускаем тесты
    - run: ./gradlew clean test


